# Generated by Django 4.2.10 on 2024-02-07 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userame', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('hospital_name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=120)),
                ('Name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=120)),
                ('Name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('mobile', models.CharField(max_length=12, unique=True)),
                ('blood_type', models.CharField(max_length=5)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=12)),
                ('weight', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
