# Generated by Django 4.2.10 on 2024-02-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
