# Generated by Django 4.2.10 on 2024-02-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_donorprofile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='user',
        ),
    ]
