# Generated by Django 4.2.10 on 2024-02-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_donorprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='userame',
            new_name='username',
        ),
        migrations.AddField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
