# Generated by Django 4.2.10 on 2024-02-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_userame_admin_username_admin_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
