# Generated by Django 4.2.10 on 2024-02-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0005_donorprofile_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donorprofile',
            options={'default_permissions': ('add', 'change', 'delete'), 'default_related_name': 'donorprofile', 'managed': True},
        ),
        migrations.RenameField(
            model_name='donorprofile',
            old_name='Name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='donorprofile_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='donorprofile_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
