# Generated by Django 4.2.10 on 2024-02-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_donorprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='two_fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
