# Generated by Django 4.2.10 on 2024-02-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_donorprofile_two_fa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='two_fa_enabled',
        ),
    ]
